export const INIT = 'INIT';
export const LOADING_EQUIPMENT_START = 'LOADING_EQUIPMENT_START';
export const LOADING_EQUIPMENT_SUCCESS = 'LOADING_EQUIPMENT_SUCCESS';
export const LOADING_EQUIPMENT_ERROR = 'LOADING_EQUIPMENT_ERROR';